---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "javaapp-service"
  namespace: "default"
  labels:
    app: "javaapp"
spec:  
  ports:
  - protocol: "TCP"
    port: 8089
    targetPort: 8080
  selector:
    app: "javaapp"
  type: "LoadBalancer"
  loadBalancerIP: ""
